/** @jest-environment jsdom */
import { loadDewy, DewyApp } from '../helpers/loadDewy';

let app: DewyApp | null = null;
afterEach(() => { if (app) { app.destroy(); app = null; } });

const STATES = ['Safe To Use', 'Use With Caution', 'Do Not Combine Yet', 'Best For Morning', 'Best For Evening',
  'Travel Optional', 'Routine Essential', 'Needs More Information', 'Check Product Directions', 'Consider Professional Advice'];

function visible(a: DewyApp): string[] {
  return Object.keys(a.api.PRODUCTS).filter((k) => a.api.PRODUCTS[k].status !== 'ARCHIVED');
}
function quiet(a: DewyApp) {
  // no Low products, and a Protect step in the morning, so no rule fires
  for (const id of visible(a)) if (a.api.PRODUCTS[id].status === 'NEARLY_EMPTY') a.api.PRODUCTS[id].status = 'ACTIVE';
  a.api.S.replenish = [];
}

describe('One Smart Recommendation', () => {
  test('at most one suggestion, only on Home, with its reason inspectable', () => {
    app = loadDewy();
    quiet(app);
    const id = visible(app)[0];
    app.api.PRODUCTS[id].status = 'NEARLY_EMPTY';
    app.tab('home');
    expect(app.all('.advisor').length).toBe(1);
    expect(app.text()).toContain('Is Running Low');
    expect(app.text()).toContain('Add It To Replenish List?');
    app.click({ act: 'toggle', key: 'advWhy' });
    expect(app.find('#why-advWhy')!.getAttribute('aria-expanded')).toBe('true');
    expect(app.text()).toContain('Not generated by AI');
    expect(app.text()).toContain('marked Low');
    for (const tab of ['cabinet', 'routine', 'discover', 'profile']) {
      app.tab(tab);
      expect(app.all('.advisor').length).toBe(0);
    }
  });

  test('priority: a low product outranks a missing sun-protection step', () => {
    app = loadDewy();
    quiet(app);
    const id = visible(app)[0];
    app.api.PRODUCTS[id].status = 'NEARLY_EMPTY';
    app.api.S.routine.am = visible(app).filter((k) => app!.api.PRODUCTS[k].category !== 'PROTECT');
    app.tab('home');
    expect(app.text()).toContain('Is Running Low');
    expect(app.text()).not.toContain('No Sun Protection Step');
  });

  test('rule: the morning routine has no sun protection step', () => {
    app = loadDewy();
    quiet(app);
    app.api.S.routine.am = visible(app).filter((k) => app!.api.PRODUCTS[k].category !== 'PROTECT');
    app.tab('home');
    expect(app.text()).toContain('Your Morning Routine Has No Sun Protection Step');
    expect(app.text()).toContain('Review Your Routine?');
    app.click({ act: 'advisor-review-am' });
    expect(app.api.S.tab).toBe('routine');
    expect(app.api.S.tod).toBe('am');
    expect(app.api.S.ui.routineEdit).toBe(true);
  });

  test('rule: an empty or fully paused Cabinet asks for a product', () => {
    app = loadDewy();
    for (const id of Object.keys(app.api.PRODUCTS)) app.api.PRODUCTS[id].status = 'ARCHIVED';
    app.tab('home');
    expect(app.text()).toContain('Add A Product To Start Building Your Routine');
    app.click('.advisor [data-act="go-add-search"]');
    expect(app.api.S.ui.add && app.api.S.ui.add.step).toBe('search');
  });

  test('no rule, no card, no empty box', () => {
    app = loadDewy();
    quiet(app);
    app.tab('home');
    expect(app.all('.advisor').length).toBe(0);
  });

  test('dismiss hides it with a record, undo restores it, and the record persists', () => {
    app = loadDewy();
    quiet(app);
    const id = visible(app)[0];
    app.api.PRODUCTS[id].status = 'NEARLY_EMPTY';
    app.tab('home');
    app.click({ act: 'advisor-dismiss' });
    expect(app.all('.advisor').length).toBe(0);
    expect(app.text()).toContain('Suggestion Hidden');
    expect(app.api.S.dismissed.length).toBe(1);
    expect(app.api.S.dismissed[0].id).toBe('low:' + id);
    expect(app.storage().dismissed.length).toBe(1);
    app.click({ act: 'advisor-undo' });
    expect(app.all('.advisor').length).toBe(1);
    expect(app.api.S.dismissed.length).toBe(0);
  });

  test('the primary action works: Replenish List gains the product, reversibly', () => {
    app = loadDewy();
    quiet(app);
    const id = visible(app)[0];
    app.api.PRODUCTS[id].status = 'NEARLY_EMPTY';
    app.tab('home');
    app.click({ act: 'replenish-add', id });
    expect(app.api.S.replenish).toEqual([id]);
    expect(app.all('.advisor').length).toBe(0);
    app.tab('cabinet');
    expect(app.text()).toContain('Replenish List');
    expect(app.text()).toContain(app.api.PRODUCTS[id].productName);
    app.click({ act: 'replenish-remove', id });
    expect(app.api.S.replenish).toEqual([]);
  });

  test('the provider boundary is swappable without touching a screen', () => {
    app = loadDewy();
    quiet(app);
    app.api.S.tab = 'home';
    const Advisor = app.api.Advisor;
    expect(Advisor).toBeTruthy();
    Advisor.provider = { name: 'Stub', generated: false, suggest: () => ({ id: 'stub:1', title: 'Stub Title', rationale: 'Stub reason.',
      why: 'Because a test said so.', state: 'Safe To Use', action: { label: 'Open Cabinet', act: 'tab', v: 'cabinet' }, dismissLabel: 'Not Now' }) };
    app.api.render();
    expect(app.text()).toContain('Stub Title');
    Advisor.provider = null;
    app.api.render();
    expect(app.all('.advisor').length).toBe(0);
  });
});

describe('Review Your Products answers as verdict cards', () => {
  test('each answer carries an allowed state, a reason, completeness, and an action', () => {
    app = loadDewy();
    app.api.S.tod = 'pm';
    app.tab('discover');
    app.click({ act: 'tab', v: 'ask' });
    for (const q of ['1', '2', '3']) {
      app.click({ act: 'ask-q', v: q });
      const state = app.find('.verdict-state')!.textContent || '';
      expect(STATES).toContain(state);
      const text = app.text();
      expect(text).toContain('Information Completeness');
      expect(text).toContain('Ingredient data: not available');
      expect(text).toContain('Not generated by AI');
      expect(app.find('.verdict .btn')).not.toBeNull();
    }
  });

  test('a pairing with no data says Needs More Information instead of guessing', () => {
    app = loadDewy();
    app.tab('discover');
    app.click({ act: 'tab', v: 'ask' });
    const ids = visible(app).filter((k) => !app!.api.PRODUCTS[k].active && app!.api.PRODUCTS[k].category !== 'SEAL').slice(0, 2);
    app.click({ act: 'ask-sel', id: ids[0] });
    app.click({ act: 'ask-sel', id: ids[1] });
    app.click({ act: 'ask-q', v: '0' });
    expect(app.find('.verdict-state')!.textContent).toBe('Needs More Information');
    expect(app.text()).not.toMatch(/safe together|guaranteed|clinical score/i);
  });

  test('Open {product} from an answer lands on that product', () => {
    app = loadDewy();
    app.api.S.tod = 'pm';
    app.tab('discover');
    app.click({ act: 'tab', v: 'ask' });
    app.click({ act: 'ask-q', v: '1' });
    const btn = app.find('.verdict [data-act="detail"]');
    expect(btn).not.toBeNull();
    const id = btn!.getAttribute('data-id');
    app.click('.verdict [data-act="detail"]');
    expect(app.api.S.tab).toBe('cabinet');
    expect(app.api.S.ui.detail).toBe(id);
  });
});
