#!/usr/bin/env node
/* Inline the Skin Chemist modules into design/dewy.html.
   The app stays one HTML file (that is how it is published). The source of
   truth for the engine is src/chemist/*.js; this script copies those files,
   in dependency order, between two markers in the HTML. Run:
     node scripts/build-chemist.js
   It is safe to run again; the block is replaced, never duplicated. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const HTML = path.join(ROOT, 'design', 'dewy.html');
const ORDER = ['dictionary', 'normalize', 'actives', 'rules', 'golden', 'engine', 'review', 'index'];
const START = '<!-- CHEMIST:START (generated by scripts/build-chemist.js; edit src/chemist instead) -->';
const END = '<!-- CHEMIST:END -->';

const bundle = ORDER.map((name) => {
  const src = fs.readFileSync(path.join(ROOT, 'src', 'chemist', name + '.js'), 'utf8');
  return '/* ---- src/chemist/' + name + '.js ---- */\n' + src;
}).join('\n');

const block = START + '\n<script>\n' + bundle + '\n</script>\n' + END;

let html = fs.readFileSync(HTML, 'utf8');
const s = html.indexOf(START), e = html.indexOf(END);
if (s > -1 && e > -1) {
  html = html.slice(0, s) + block + html.slice(e + END.length);
} else {
  /* first time: place the bundle before the app's own <script> so the app can read window.DewyChemist */
  const anchor = html.indexOf('<script>\n(function(){');
  if (anchor < 0) throw new Error('Could not find the app script to place the Skin Chemist before.');
  html = html.slice(0, anchor) + block + '\n' + html.slice(anchor);
}
fs.writeFileSync(HTML, html);
console.log('Skin Chemist inlined: ' + Math.round(bundle.length / 1024) + ' KB from ' + ORDER.length + ' modules.');
